###post user
POST http://localhost:8000/api/v1/register
Content-Type: application/json

{
    "username":"sulav",
    "email":"sulav13@gmail.com",
    "password":"123456"
}

###login user
POST http://localhost:8000/api/v1/login
Content-Type: application/json

{
    "email":"sulav@gmail.com",
    "password":"123456"
}

### get user
GET http://localhost:8000/api/v1/630821051222f1586f5a9eae